# pyproject.toml at repo root
[tool.uv]
workspace = true
members = [
    "packages/pylothouse-core",
    "packages/pylothouse-nicefigs",
    "packages/pylothouse",  # metapackage
]

[tool.ruff]
target-version = "py310"
extend-select = ["I","UP","B","SIM","PL"]

[tool.mypy]
strict = true
python_version = "3.10"

[tool.pytest.ini_options]
testpaths = ["packages"]